runtime: custom
env: flex

# Configuration pour Google Cloud Run
manual_scaling:
  instances: 1

# Variables d'environnement pour Streamlit
env_variables:
  STREAMLIT_SERVER_PORT: "8080"
  STREAMLIT_SERVER_ADDRESS: "0.0.0.0"
  STREAMLIT_SERVER_HEADLESS: "true"
  STREAMLIT_BROWSER_GATHER_USAGE_STATS: "false"

# Configuration des ressources
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

# Configuration réseau
network:
  forwarded_ports:
    - 8080

# Configuration de santé
readiness_check:
  path: "/_stcore/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: "/_stcore/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2